/**
 * Lender Lens (Stage 27, innovation #20) — scorecard projector/service.
 *
 * Projector doctrine (same as AnalyticsProjectorService): there is no
 * in-process timer — the scorecard is derived on first request for a
 * (lender, version, period) and then served immutably from
 * analytics.lender_scorecards. Derivation replays deterministic inputs:
 *   - lender attribution: borrowers the partner recorded a disbursement or
 *     programme enrolment for (partner.disbursement.recorded /
 *     partner.enrolment.recorded outbox events — the outbox-fed pattern);
 *   - portfolio facts: credit loans + repayment schedules of those
 *     borrowers, borrower STATE from profiles (aggregate geo bands only);
 *   - PAR: the shared accumulation in modules/credit/par.ts.
 *
 * Fail-closed & honesty:
 *   - feature flag `lender-lens` (default OFF) gates every entry point;
 *   - staleness: the analytics projector heartbeat (star stats projection
 *     probe) older than the version's staleThresholdMs marks the served
 *     scorecard with a `stale` badge — the badge is computed at SERVE time
 *     so it never freezes a lie into the immutable payload;
 *   - payload assembly runs through assertPayloadHasNoPii before storage.
 */
import {
  BadRequestException,
  Inject,
  Injectable,
  NotFoundException
} from '@nestjs/common';
import type { User } from '@agric-platform/shared';
import { newId } from '../../common/async-repository.js';
import { FeatureFlagsService } from '../../common/feature-flags/feature-flags.service.js';
import { TelemetryService } from '../../common/telemetry/telemetry.service.js';
import { DomainEventsService } from '../../core/domain-events.service.js';
import {
  ANALYTICS_STAR_REPOSITORY,
  CREDIT_LOAN_REPOSITORY,
  CREDIT_REPAYMENT_REPOSITORY,
  OUTBOX_REPOSITORY,
  PROFILE_REPOSITORY
} from '../../database/persistence.tokens.js';
import type { AnalyticsStarRepository } from '../../database/repositories/analytics-star.repository.js';
import type {
  CreditLoanRepository,
  CreditRepaymentRepository
} from '../../database/repositories/credit-suite.repository.js';
import {
  LENDER_SCORECARD_REPOSITORY,
  type LenderScorecardRepository,
  type LenderScorecardRow
} from '../../database/repositories/lender-scorecard.repository.js';
import type { OutboxRepository } from '../../database/repositories/outbox.repository.js';
import type { ProfileRepository } from '../../database/repositories/profile.repository.js';
import {
  assertPayloadHasNoPii,
  assertPeriodFormat,
  assembleScorecard,
  canonicalSha256,
  computeBenchmarkCells,
  normalizeDefinition,
  scorecardPayloadHash,
  type ScorecardLoanFact,
  type ScorecardVersionDefinition
} from './lender-scorecard.js';
import { ANALYTICS_PROJECTOR_CONSUMER } from './projector.service.js';
import { lagosDateKey } from './retention.js';

export const LENDER_LENS_FLAG = 'lender-lens';

/** Outbox events that attribute a borrower to a lender partner (v1 rule). */
export const LENDER_ATTRIBUTION_EVENTS = [
  'partner.disbursement.recorded',
  'partner.enrolment.recorded'
] as const;

export interface PublishVersionInput {
  version: string;
  definition: unknown;
}

export interface ScorecardEnvelope {
  /** The immutable, hash-addressed payload. */
  payload: LenderScorecardRow['payload'];
  payloadHash: string;
  generatedAt: string;
  /** True when freshly generated by this call (false = served from store). */
  created: boolean;
  /** Honest staleness badge from the analytics projector heartbeat probe. */
  stale: boolean;
  projectorLagMs: number | null;
}

@Injectable()
export class LenderScorecardService {
  constructor(
    @Inject(LENDER_SCORECARD_REPOSITORY)
    private readonly scorecards: LenderScorecardRepository,
    @Inject(CREDIT_LOAN_REPOSITORY) private readonly loans: CreditLoanRepository,
    @Inject(CREDIT_REPAYMENT_REPOSITORY) private readonly repayments: CreditRepaymentRepository,
    @Inject(PROFILE_REPOSITORY) private readonly profiles: ProfileRepository,
    @Inject(OUTBOX_REPOSITORY) private readonly outbox: OutboxRepository,
    @Inject(ANALYTICS_STAR_REPOSITORY) private readonly star: AnalyticsStarRepository,
    private readonly events: DomainEventsService,
    private readonly flags: FeatureFlagsService,
    private readonly telemetry: TelemetryService
  ) {}

  /** Fail-closed flag gate (404 — the surface does not exist when off). */
  private async requireEnabled(context: { userId?: string; roles?: string[] }): Promise<void> {
    const enabled = await this.flags.isEnabled(LENDER_LENS_FLAG, context);
    if (!enabled) {
      throw new NotFoundException(`Feature '${LENDER_LENS_FLAG}' is not enabled`);
    }
  }

  /** Admin: publish an immutable scorecard version definition. */
  async publishVersion(actor: User, input: PublishVersionInput) {
    await this.requireEnabled({ userId: actor.id, roles: actor.roles });
    if (!input.version || typeof input.version !== 'string') {
      throw new BadRequestException('version is required');
    }
    let definition: ScorecardVersionDefinition;
    try {
      definition = normalizeDefinition(input.definition ?? {});
    } catch (error) {
      throw new BadRequestException(
        error instanceof Error ? error.message : 'invalid scorecard definition'
      );
    }
    const { row, created } = await this.scorecards.publishVersion({
      version: input.version,
      definition,
      publishedAt: new Date().toISOString(),
      publishedBy: actor.id
    });
    if (created) {
      await this.events.publish(
        'analytics.scorecard_version.published',
        {
          tenantId: 'platform',
          version: row.version,
          definitionHash: canonicalSha256(row.definition),
          publishedBy: actor.id
        },
        actor.id
      );
    }
    return { ...row, created };
  }

  /**
   * Generate-or-serve the scorecard for (lender, version, period). First
   * call derives and stores the immutable payload; later calls serve the
   * stored row. The staleness badge is recomputed on every serve.
   */
  async scorecard(
    lenderPartnerId: string,
    period?: string,
    version?: string,
    context: { userId?: string; roles?: string[] } = {}
  ): Promise<ScorecardEnvelope> {
    await this.requireEnabled(context);
    const resolvedPeriod = period ?? lagosDateKey(new Date()).slice(0, 7);
    try {
      assertPeriodFormat(resolvedPeriod);
    } catch (error) {
      throw new BadRequestException(
        error instanceof Error ? error.message : 'invalid period'
      );
    }
    const versionRow = version
      ? await this.scorecards.scorecardVersion(version)
      : await this.scorecards.latestScorecardVersion();
    if (!versionRow) {
      throw new NotFoundException(
        version
          ? `scorecard version '${version}' is not published`
          : 'no lender scorecard version is published yet'
      );
    }

    const existing = await this.scorecards.scorecard(
      lenderPartnerId,
      versionRow.version,
      resolvedPeriod
    );
    const row = existing ?? (await this.generate(lenderPartnerId, versionRow, resolvedPeriod));
    const { stale, lagMs } = await this.staleness(versionRow.definition);
    return {
      payload: row.payload,
      payloadHash: row.payloadHash,
      generatedAt: row.generatedAt,
      created: !existing,
      stale,
      projectorLagMs: lagMs
    };
  }

  /** Derives and stores the immutable scorecard (span + counter + event). */
  private async generate(
    lenderPartnerId: string,
    versionRow: { version: string; definition: ScorecardVersionDefinition },
    period: string
  ): Promise<LenderScorecardRow> {
    return this.telemetry.withSpan(
      'analytics.lender_scorecard.generate',
      { 'tenant.id': lenderPartnerId, version: versionRow.version, period },
      async () => {
        const facts = await this.collectFacts(lenderPartnerId);
        const payload = assembleScorecard(
          versionRow.definition,
          lenderPartnerId,
          versionRow.version,
          period,
          facts
        );
        assertPayloadHasNoPii(payload);
        const { row, created } = await this.scorecards.insertScorecard({
          id: newId('lsc'),
          lenderPartnerId,
          version: versionRow.version,
          period,
          payload,
          payloadHash: scorecardPayloadHash(payload),
          generatedAt: new Date().toISOString()
        });
        if (created) {
          this.telemetry.increment('analytics.scorecards_generated_total', 1, {
            'tenant.id': lenderPartnerId
          });
          await this.events.publish(
            'analytics.lender_scorecard.generated',
            {
              tenantId: lenderPartnerId,
              scorecardId: row.id,
              lenderPartnerId,
              version: row.version,
              period: row.period,
              payloadHash: row.payloadHash
            },
            lenderPartnerId
          );
          await this.recomputeBenchmarks(row.version, row.period, versionRow.definition);
        }
        return row;
      }
    );
  }

  /**
   * Outbox-fed attribution + OLTP facts. Aggregate-safe: the only borrower
   * attribute carried forward is the profile STATE (a geo band); user ids
   * are used for join keys only and never enter the payload.
   */
  private async collectFacts(lenderPartnerId: string): Promise<ScorecardLoanFact[]> {
    const borrowerIds = new Set<string>();
    const records = await this.outbox.listRecords();
    for (const record of records) {
      const event = record.event;
      if (!(LENDER_ATTRIBUTION_EVENTS as readonly string[]).includes(event.name)) {
        continue;
      }
      const payload = event.payload as { partnerId?: string; userId?: string };
      if (payload.partnerId === lenderPartnerId && payload.userId) {
        borrowerIds.add(payload.userId);
      }
    }

    const facts: ScorecardLoanFact[] = [];
    const loans = await this.loans.all();
    for (const loan of loans) {
      if (!borrowerIds.has(loan.applicantUserId)) {
        continue;
      }
      const [schedule, profile] = await Promise.all([
        this.repayments.find({ loanId: loan.id }),
        this.profiles.findByUserId(loan.applicantUserId)
      ]);
      facts.push({
        productId: loan.productId,
        ...(profile?.location.state ? { borrowerState: profile.location.state } : {}),
        status: loan.status,
        createdAt: loan.createdAt,
        repayments: schedule.map((repayment) => ({
          dueAt: repayment.dueAt,
          amountKobo: repayment.amountKobo,
          status: repayment.status,
          ...(repayment.paidAt ? { paidAt: repayment.paidAt } : {})
        }))
      });
    }
    return facts;
  }

  /** Recomputes the k-anonymity-gated benchmark cells for (version, period). */
  private async recomputeBenchmarks(
    version: string,
    period: string,
    definition: ScorecardVersionDefinition
  ): Promise<void> {
    const rows = await this.scorecards.scorecardsForPeriod(version, period);
    const cells = computeBenchmarkCells(
      definition,
      rows.map((row) => ({ lenderPartnerId: row.lenderPartnerId, payload: row.payload }))
    );
    const generatedAt = new Date().toISOString();
    for (const cell of cells) {
      await this.scorecards.upsertBenchmark({ ...cell, version, period, generatedAt });
    }
  }

  /** Published versions (admin surface). */
  async listVersions(context: { userId?: string; roles?: string[] } = {}) {
    await this.requireEnabled(context);
    return this.scorecards.listScorecardVersions();
  }

  /** Benchmark cells for a (version, period) — admin/diagnostics surface. */
  async benchmarks(
    version: string,
    period: string,
    context: { userId?: string; roles?: string[] } = {}
  ) {
    await this.requireEnabled(context);
    return this.scorecards.benchmarks(version, period);
  }

  /** Staleness from the analytics projector heartbeat probe (star stats). */
  private async staleness(
    definition: ScorecardVersionDefinition
  ): Promise<{ stale: boolean; lagMs: number | null }> {
    const stats = await this.star.stats(ANALYTICS_PROJECTOR_CONSUMER);
    const lastRunAt = stats.projection?.lastRunAt;
    if (!lastRunAt) {
      // No heartbeat at all: the projector never ran here — honestly stale.
      return { stale: true, lagMs: null };
    }
    const lagMs = Math.max(0, Date.now() - Date.parse(lastRunAt));
    return { stale: lagMs > definition.staleThresholdMs, lagMs };
  }
}
