/**
 * Voice Teller intent router (Stage 27, Innovation 6) — a pure,
 * deterministic grammar-slot router for transactional voice intents. Two
 * input modalities resolve to the same four read-only account intents:
 *
 *   DTMF    — the IVR account-menu digit (1..5), see ACCOUNT_MENU_DTMF.
 *   ASR slots — keyword-phrase matching over the (already transcribed)
 *             utterance, per locale with English fallback.
 *
 * There is NO free-form generation for account data: anything that does
 * not resolve to exactly one intent returns `undefined`, and the caller
 * routes the turn to the existing agronomy RAG flow or human escalation,
 * unchanged. Account values are read from the ledger/credit/vsla/voucher
 * read models by the service layer and rendered through the fixed speech
 * templates in intent-templates.ts — never generated by a model.
 *
 * Locale keyword content for ha/yo/ig is a first-pass deterministic
 * grammar; native-speaker review is a content dependency (HANDOFF.md).
 * The matching PRECEDENCE rule is what keeps the router deterministic:
 * the intent with the longest matched phrase wins; ties break in catalog
 * (VOICE_INTENT_IDS) order.
 */

export const VOICE_TELLER_FLAG = 'voice-teller';

/** The complete transactional-intent catalog (read-only account facts). */
export const VOICE_INTENT_IDS = [
  'balance.savings',
  'balance.float',
  'loan.next_installment',
  'vsla.position',
  'voucher.status'
] as const;
export type VoiceIntentId = (typeof VOICE_INTENT_IDS)[number];

/** Locales with speech templates + ASR grammars this wave. */
export const VOICE_INTENT_LOCALES = ['en', 'ha', 'yo', 'ig'] as const;
export type VoiceIntentLocale = (typeof VOICE_INTENT_LOCALES)[number];

/** Unknown/unsupported locales fall back to English templates + grammar. */
export function normalizeVoiceIntentLocale(locale?: string): VoiceIntentLocale {
  const lowered = (locale ?? 'en').trim().toLowerCase();
  return (VOICE_INTENT_LOCALES as readonly string[]).includes(lowered)
    ? (lowered as VoiceIntentLocale)
    : 'en';
}

/* ---------------------------------------------------------------- DTMF -- */

/**
 * IVR account-menu digit → intent. The menu prompt in ivr/call-flow.ts
 * reads these in key order, so the mapping and the spoken menu can never
 * drift apart.
 */
export const ACCOUNT_MENU_DTMF: Readonly<Record<string, VoiceIntentId>> = {
  '1': 'balance.savings',
  '2': 'balance.float',
  '3': 'loan.next_installment',
  '4': 'vsla.position',
  '5': 'voucher.status'
};

export function intentForDtmf(digit: string): VoiceIntentId | undefined {
  return ACCOUNT_MENU_DTMF[digit.trim()];
}

/* -------------------------------------------------------------- ASR ----- */

/**
 * Grammar-slot keyword phrases per intent per locale. Matching is
 * substring-based over the lowercase, punctuation-stripped transcript;
 * the English grammar ALWAYS applies (code-switching is the norm on
 * Nigerian voice channels) with the caller's locale grammar added on top.
 */
const ASR_GRAMMAR: Readonly<Record<VoiceIntentId, Readonly<Record<VoiceIntentLocale, readonly string[]>>>> = {
  'balance.savings': {
    en: ['savings balance', 'savings', 'my balance', 'account balance', 'balance', 'how much do i have'],
    ha: ['ajiyar kudi', 'ajiya', 'balan', 'kudin da nake da shi'],
    yo: ['owo ifowopamo', 'ifowopamo', 'balanse', 'owo mi'],
    ig: ['ego echekwara', 'echekwa', 'balans', 'ego m nwere']
  },
  'balance.float': {
    en: ['float balance', 'agent float', 'float', 'my float'],
    ha: ['float', 'kudin aiki na wakili'],
    yo: ['float', 'owo aaso'],
    ig: ['float', 'ego ozi']
  },
  'loan.next_installment': {
    en: ['next installment', 'installment', 'instalment', 'next repayment', 'repayment', 'loan payment', 'when do i pay', 'next payment'],
    ha: ['biyan bashi', 'bashi', 'raba biya', 'biya'],
    yo: ['gbese', 'sanwo gbese', 'sanwo', 'bese'],
    ig: ['kwuo ugwo', 'ugwo mgbinye', 'mgbinye', 'ugwo']
  },
  'vsla.position': {
    en: ['vsla', 'group savings position', 'group position', 'my group savings', 'share out', 'shareout'],
    ha: ['vsla', 'kungiya', 'ajiyar kungiya', 'rabo'],
    yo: ['vsla', 'ajo', 'esusu', 'egbe'],
    ig: ['vsla', 'isusu', 'otu', 'ekeso']
  },
  'voucher.status': {
    en: ['voucher status', 'voucher', 'input voucher', 'subsidy voucher', 'my voucher'],
    ha: ['voucher', 'baucar', 'tallafi', 'tallafin'],
    yo: ['voucher', 'faucha', 'irawo'],
    ig: ['voucher', 'vaucha', 'enyemaka']
  }
};

/** Lowercases, strips punctuation (keeps letters/digits/spaces), collapses whitespace. */
export function normalizeTranscript(transcript: string): string {
  return transcript
    .toLowerCase()
    .replace(/[^a-z0-9 ]/g, ' ')
    .split(' ')
    .filter((word) => word.length > 0)
    .join(' ');
}

interface GrammarMatch {
  intent: VoiceIntentId;
  /** Length of the longest matched phrase (precedence rule). */
  matchedLength: number;
}

/**
 * Resolves an ASR transcript to exactly one intent, or undefined when the
 * utterance matches nothing (route to agronomy RAG / escalation). The
 * longest matched phrase wins; ties break in catalog order. A transcript
 * mentioning two intents with different phrase lengths resolves to the
 * more specific (longer) phrase — e.g. 'float balance' beats 'balance'.
 */
export function intentForTranscript(transcript: string, locale?: string): VoiceIntentId | undefined {
  const normalized = normalizeTranscript(transcript);
  if (normalized.length === 0) {
    return undefined;
  }
  const resolvedLocale = normalizeVoiceIntentLocale(locale);
  let best: GrammarMatch | undefined;
  for (const intent of VOICE_INTENT_IDS) {
    const grammar = ASR_GRAMMAR[intent];
    const phrases = resolvedLocale === 'en' ? grammar.en : [...grammar.en, ...grammar[resolvedLocale]];
    for (const phrase of phrases) {
      if (normalized.includes(phrase) && (!best || phrase.length > best.matchedLength)) {
        best = { intent, matchedLength: phrase.length };
      }
    }
  }
  return best?.intent;
}

/* ------------------------------------------------------ number speech --- */

/**
 * Deterministic thousands grouping (comma-separated), implemented in-repo
 * so known-answer tests never depend on the host ICU build.
 */
export function formatIntegerSpeech(value: number): string {
  if (!Number.isSafeInteger(value) || value < 0) {
    throw new RangeError(`formatIntegerSpeech expects a non-negative safe integer, got ${value}`);
  }
  const digits = String(value);
  const groups: string[] = [];
  for (let end = digits.length; end > 0; end -= 3) {
    groups.unshift(digits.slice(Math.max(0, end - 3), end));
  }
  return groups.join(',');
}

/** Locale glue words for money speech (naira/kobo are loanwords everywhere). */
const MONEY_WORDS: Readonly<Record<VoiceIntentLocale, { and: string }>> = {
  en: { and: 'and' },
  ha: { and: 'da' },
  yo: { and: 'ati' },
  ig: { and: 'na' }
};

/**
 * kobo → spoken naira. 123456 kobo, en → '1,234 naira and 56 kobo'.
 * Zero-kobo amounts omit the kobo clause: 100000 → '1,000 naira'.
 * Sub-naira amounts speak kobo only: 75 → '75 kobo'.
 */
export function speakMoneyKobo(amountKobo: number, locale?: string): string {
  if (!Number.isSafeInteger(amountKobo) || amountKobo < 0) {
    throw new RangeError(`speakMoneyKobo expects a non-negative safe integer, got ${amountKobo}`);
  }
  const words = MONEY_WORDS[normalizeVoiceIntentLocale(locale)];
  const naira = Math.floor(amountKobo / 100);
  const kobo = amountKobo % 100;
  if (naira === 0) {
    return `${formatIntegerSpeech(kobo)} kobo`;
  }
  const nairaPart = `${formatIntegerSpeech(naira)} naira`;
  return kobo === 0 ? nairaPart : `${nairaPart} ${words.and} ${formatIntegerSpeech(kobo)} kobo`;
}

/** Spoken month names per locale (loanword forms, ASCII — native review pending). */
const MONTH_NAMES: Readonly<Record<VoiceIntentLocale, readonly string[]>> = {
  en: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
  ha: ['Janairu', 'Fabrairu', 'Maris', 'Afrilu', 'Mayu', 'Yuni', 'Yuli', 'Agusta', 'Satumba', 'Oktoba', 'Nuwamba', 'Disamba'],
  yo: ['Januari', 'Februwari', 'Masi', 'Eeprili', 'Meeyi', 'Juuni', 'Juulai', 'Ogisti', 'Septemba', 'Okitoba', 'Nofemba', 'Disemba'],
  ig: ['Januari', 'Februari', 'Maachi', 'Eprel', 'Mee', 'Juun', 'Julai', 'Ogost', 'Septemba', 'Oktoba', 'Novemba', 'Disemba']
};

/**
 * ISO instant → spoken date, e.g. '2026-10-05T…' en → '5 October 2026'.
 * Deterministic (UTC calendar fields); invalid input throws so a malformed
 * due date can never be smuggled into a spoken answer.
 */
export function speakDate(iso: string, locale?: string): string {
  const date = new Date(iso);
  if (Number.isNaN(date.getTime())) {
    throw new RangeError(`speakDate expects an ISO date, got '${iso}'`);
  }
  const names = MONTH_NAMES[normalizeVoiceIntentLocale(locale)];
  return `${date.getUTCDate()} ${names[date.getUTCMonth()]} ${date.getUTCFullYear()}`;
}
