#!/usr/bin/env node
/**
 * Generates the real PNG install icons referenced by
 * public/manifest.webmanifest from the committed vector source
 * (public/icon.svg), using sharp (already a Next.js dependency — no new
 * packages).
 *
 * Outputs (all committed binary assets, regenerated by `npm run icons:generate`):
 *   public/icon-192.png            192x192  purpose "any"
 *   public/icon-512.png            512x512  purpose "any"
 *   public/icon-maskable-192.png   192x192  purpose "maskable" (80% safe zone)
 *   public/icon-maskable-512.png   512x512  purpose "maskable" (80% safe zone)
 *   public/apple-touch-icon.png    180x180  flattened (iOS forbids transparency)
 *
 * Maskable icons keep the artwork inside the center 80% safe zone: the SVG
 * is scaled to 80% and composited over the solid brand background so
 * launchers can crop to circle/squircle/teardrop without clipping the mark.
 */
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import sharp from 'sharp';

const publicDir = path.resolve(
  fileURLToPath(new URL('.', import.meta.url)),
  '..',
  'public'
);

/** Brand green — matches the icon.svg backdrop and manifest theme_color. */
const BRAND_BACKGROUND = '#2f5d3f';
/** Maskable safe zone: artwork must live inside the center 80%. */
const SAFE_ZONE = 0.8;
/** Render the SVG well above target size, then downscale (crisp edges). */
const SVG_DENSITY = 384;

const svg = await readFile(path.join(publicDir, 'icon.svg'));

function svgSharp() {
  return sharp(svg, { density: SVG_DENSITY });
}

/** purpose "any": rasterize the mark as-is (rounded-square brand tile). */
async function writeAnyIcon(size, filename) {
  const out = path.join(publicDir, filename);
  await svgSharp().resize(size, size).png().toFile(out);
  return out;
}

/** purpose "maskable": artwork scaled into the 80% safe zone on solid brand. */
async function writeMaskableIcon(size, filename) {
  const inner = Math.round(size * SAFE_ZONE);
  const artwork = await svgSharp().resize(inner, inner).png().toBuffer();
  const out = path.join(publicDir, filename);
  await sharp({
    create: {
      width: size,
      height: size,
      channels: 4,
      background: BRAND_BACKGROUND
    }
  })
    .composite([{ input: artwork, gravity: 'center' }])
    .png()
    .toFile(out);
  return out;
}

/** Apple touch icon: iOS applies its own mask and cannot use transparency. */
async function writeAppleTouchIcon(size, filename) {
  const out = path.join(publicDir, filename);
  await svgSharp()
    .resize(size, size)
    .flatten({ background: BRAND_BACKGROUND })
    .png()
    .toFile(out);
  return out;
}

const written = await Promise.all([
  writeAnyIcon(192, 'icon-192.png'),
  writeAnyIcon(512, 'icon-512.png'),
  writeMaskableIcon(192, 'icon-maskable-192.png'),
  writeMaskableIcon(512, 'icon-maskable-512.png'),
  writeAppleTouchIcon(180, 'apple-touch-icon.png')
]);

for (const file of written) {
  console.log(`wrote ${path.relative(process.cwd(), file)}`);
}
