/**
 * Expo app config (replaces app.json so permissions/infoPlist entries can be
 * justified inline). Store-facing identity matches the web platform
 * (apps/web/public/manifest.webmanifest: "AgricPlatform").
 *
 * EAS overrides `extra.apiBaseUrl` per build profile via eas.json env —
 * no secrets are ever bundled in this file.
 */
module.exports = {
  expo: {
    name: 'AgricPlatform',
    slug: 'agric-platform',
    version: '1.0.0',
    orientation: 'portrait',
    userInterfaceStyle: 'light',
    backgroundColor: '#ffffff',
    primaryColor: '#2f5d3f',
    // OTA-update runtime version tracks the native app version (Expo
    // "appVersion" policy); takes effect once expo-updates is enabled.
    runtimeVersion: { policy: 'appVersion' },

    // Generated by `npm run icons:generate -w @agric-platform/mobile` from
    // the committed vector mark (apps/web/public/icon.svg) — real binary
    // assets, committed under assets/.
    icon: './assets/icon.png',
    splash: {
      image: './assets/splash.png',
      resizeMode: 'contain',
      backgroundColor: '#2f5d3f'
    },

    ios: {
      supportsTablet: true,
      bundleIdentifier: 'com.agricplatform.app',
      buildNumber: '1',
      infoPlist: {
        // Encryption declaration: the app uses only TLS/HTTPS via the OS and
        // Expo-standard crypto, so it is exempt — setting this avoids the
        // App Store Connect export-compliance prompt on every upload.
        ITSAppUsesNonExemptEncryption: false
        // Deliberately NO NSCameraUsageDescription / NSPhotoLibrary… /
        // NSLocation… keys: the app never accesses camera, photos, location,
        // contacts or microphone, and review rejects boilerplate prompts.
      }
    },

    android: {
      package: 'com.agricplatform.app',
      versionCode: 1,
      // Minimal permission set. Expo always adds INTERNET (required for the
      // API client); everything else is opt-in and the app needs nothing
      // else: no camera/location/contacts/storage access. Declaring []
      // strips the default permissions Expo would otherwise merge in, which
      // keeps the Play data-safety/permission declarations honest.
      permissions: [],
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundColor: '#2f5d3f'
      },
      edgeToEdgeEnabled: true
    },

    extra: {
      apiBaseUrl: 'http://localhost:3001/api/v1'
      // NOTE: no `eas.projectId` here — it is generated by `eas init` per
      // environment and must not be invented. EAS_TOKEN lives in CI secrets.
    }
  }
};
