/**
 * Expo app config (replaces app.json so permissions/infoPlist entries can be
 * justified inline). Store-facing identity matches the web platform
 * (apps/web/public/manifest.webmanifest: "AgricPlatform").
 *
 * EAS overrides `extra.apiBaseUrl` per build profile via eas.json env —
 * no secrets are ever bundled in this file.
 */
module.exports = {
  expo: {
    name: 'AgricPlatform',
    slug: 'agric-platform',
    version: '1.0.0',
    orientation: 'portrait',
    userInterfaceStyle: 'light',
    backgroundColor: '#ffffff',
    primaryColor: '#2f5d3f',
    // Deep-link scheme (audit P1-13): agricplatform:// links route into the
    // app once deep-link screens are wired.
    scheme: 'agricplatform',
    // OTA updates (expo-updates): the runtime version tracks the native app
    // version ("appVersion" policy). The updates URL needs the EAS project
    // ID generated by `eas init` — the all-zero UUID below is a documented
    // placeholder, NOT a real project; replace it right after `eas init`
    // (see docs/mobile/store-submission.md). Channels come from eas.json
    // build profiles (development/preview/production).
    runtimeVersion: { policy: 'appVersion' },
    updates: {
      url: 'https://u.expo.dev/00000000-0000-0000-0000-000000000000'
    },

    // Generated by `npm run icons:generate -w @agric-platform/mobile` from
    // the committed vector mark (apps/web/public/icon.svg) — real binary
    // assets, committed under assets/.
    icon: './assets/icon.png',
    splash: {
      image: './assets/splash.png',
      resizeMode: 'contain',
      backgroundColor: '#2f5d3f'
    },

    plugins: [
      'expo-secure-store',
      [
        'expo-location',
        {
          // Android permission rationale shown by the config plugin; the
          // iOS string lives in infoPlist below. Honest copy: GPS is used
          // ONLY for plot boundary/centre mapping.
          locationWhenInUsePermission:
            'AgricPlatform uses your location to map your farm plots (centre point and boundary) while you are using the app.'
        }
      ],
      'expo-updates'
    ],

    ios: {
      supportsTablet: true,
      bundleIdentifier: 'com.agricplatform.app',
      buildNumber: '1',
      infoPlist: {
        // Encryption declaration: the app uses only TLS/HTTPS via the OS and
        // Expo-standard crypto, so it is exempt — setting this avoids the
        // App Store Connect export-compliance prompt on every upload.
        ITSAppUsesNonExemptEncryption: false,
        // Plot capture maps farm boundaries with GPS (audit P0-2). Honest
        // copy — the app never tracks location in the background and never
        // uses location for anything else.
        NSLocationWhenInUseUsageDescription:
          'AgricPlatform uses your location to map your farm plots (centre point and boundary) while you are using the app.'
        // Deliberately NO NSCameraUsageDescription / NSPhotoLibrary… /
        // contacts/microphone keys: those are unused and review rejects
        // boilerplate prompts.
      }
    },

    android: {
      package: 'com.agricplatform.app',
      versionCode: 1,
      // Explicit permission set (audit P0-2): the plot-capture GPS feature
      // needs precise location, so the earlier `permissions: []` strip was
      // replaced — keeping it would have stripped ACCESS_FINE_LOCATION and
      // silently broken GPS in production builds. Expo always adds
      // INTERNET (required for the API client); everything else stays
      // opt-in: no camera/contacts/storage access.
      permissions: ['ACCESS_FINE_LOCATION'],
      adaptiveIcon: {
        foregroundImage: './assets/adaptive-icon.png',
        backgroundColor: '#2f5d3f'
      },
      edgeToEdgeEnabled: true
    },

    extra: {
      // API base URL comes from the EAS build profile env (eas.json sets
      // API_BASE_URL per profile); the localhost default is for `expo
      // start` against a locally-running API only (audit P0-3).
      apiBaseUrl: process.env.API_BASE_URL ?? 'http://localhost:3001/api/v1'
      // NOTE: no `eas.projectId` here — it is generated by `eas init` per
      // environment and must not be invented. EAS_TOKEN lives in CI secrets.
    }
  }
};
