#!/usr/bin/env node
/**
 * Generates the real PNG store/launcher assets referenced by app.config.js
 * from the platform's committed vector source (apps/web/public/icon.svg —
 * the same mark the web PWA icons are generated from), using sharp (already
 * a hoisted monorepo dependency via Next.js — no new packages).
 *
 * Outputs (all committed binary assets, regenerated by
 * `npm run icons:generate -w @agric-platform/mobile`):
 *   assets/icon.png           1024x1024  App Store / Play icon (flattened —
 *                                        Apple forbids transparency)
 *   assets/adaptive-icon.png  1024x1024  Android adaptive-icon FOREGROUND:
 *                                        artwork inside the center 66% safe
 *                                        zone on transparency (background
 *                                        colour comes from app.config.js)
 *   assets/splash.png         1284x2778  splash screen: brand background with
 *                                        the mark centred at ~40% width
 */
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import sharp from 'sharp';

const mobileDir = path.resolve(fileURLToPath(new URL('.', import.meta.url)), '..');
const assetsDir = path.join(mobileDir, 'assets');
const svg = await readFile(path.resolve(mobileDir, '../web/public/icon.svg'));

/** Brand green — matches icon.svg's backdrop and the web theme_color. */
const BRAND_BACKGROUND = '#2f5d3f';
/** Android adaptive icons mask the outer third — keep art inside 66%. */
const ADAPTIVE_SAFE_ZONE = 0.66;
/** Render the SVG well above target size, then downscale (crisp edges). */
const SVG_DENSITY = 384;

function svgSharp() {
  return sharp(svg, { density: SVG_DENSITY });
}

/** Store icon: full-bleed mark, flattened (iOS forbids alpha). */
async function writeStoreIcon(size, filename) {
  const out = path.join(assetsDir, filename);
  await svgSharp().resize(size, size).flatten({ background: BRAND_BACKGROUND }).png().toFile(out);
  return out;
}

/** Adaptive foreground: artwork in the 66% safe zone over transparency. */
async function writeAdaptiveForeground(size, filename) {
  const inner = Math.round(size * ADAPTIVE_SAFE_ZONE);
  const artwork = await svgSharp().resize(inner, inner).png().toBuffer();
  const out = path.join(assetsDir, filename);
  await sharp({
    create: { width: size, height: size, channels: 4, background: { r: 0, g: 0, b: 0, alpha: 0 } }
  })
    .composite([{ input: artwork, gravity: 'center' }])
    .png()
    .toFile(out);
  return out;
}

/** Splash: solid brand background with the mark centred at ~40% width. */
async function writeSplash(width, height, filename) {
  const mark = await svgSharp()
    .resize(Math.round(width * 0.4), Math.round(width * 0.4))
    .png()
    .toBuffer();
  const out = path.join(assetsDir, filename);
  await sharp({
    create: { width, height, channels: 4, background: BRAND_BACKGROUND }
  })
    .composite([{ input: mark, gravity: 'center' }])
    .png()
    .toFile(out);
  return out;
}

const written = await Promise.all([
  writeStoreIcon(1024, 'icon.png'),
  writeAdaptiveForeground(1024, 'adaptive-icon.png'),
  writeSplash(1284, 2778, 'splash.png')
]);

for (const file of written) {
  console.log(`wrote ${path.relative(process.cwd(), file)}`);
}
