/**
 * DI tokens for the persistence wave. Repositories are provided by the
 * global DatabaseModule; stores and the Redis client by the global
 * RedisModule. Services inject the port interfaces behind these tokens so
 * the in-memory and PostgreSQL implementations stay swappable by config.
 */
export const PG_POOL = Symbol('PG_POOL');

export const USER_REPOSITORY = Symbol('USER_REPOSITORY');
export const PROFILE_REPOSITORY = Symbol('PROFILE_REPOSITORY');
export const CONSENT_REPOSITORY = Symbol('CONSENT_REPOSITORY');
export const DELETION_REQUEST_REPOSITORY = Symbol('DELETION_REQUEST_REPOSITORY');
export const COURSE_REPOSITORY = Symbol('COURSE_REPOSITORY');
export const ENROLMENT_REPOSITORY = Symbol('ENROLMENT_REPOSITORY');
export const CERTIFICATE_REPOSITORY = Symbol('CERTIFICATE_REPOSITORY');
export const FORUM_TOPIC_REPOSITORY = Symbol('FORUM_TOPIC_REPOSITORY');
export const MENTOR_REQUEST_REPOSITORY = Symbol('MENTOR_REQUEST_REPOSITORY');
export const TOPIC_FLAG_REPOSITORY = Symbol('TOPIC_FLAG_REPOSITORY');
export const OPPORTUNITY_REPOSITORY = Symbol('OPPORTUNITY_REPOSITORY');
export const APPLICATION_REPOSITORY = Symbol('APPLICATION_REPOSITORY');
export const CHAPTER_REPOSITORY = Symbol('CHAPTER_REPOSITORY');
export const CHAPTER_EVENT_REPOSITORY = Symbol('CHAPTER_EVENT_REPOSITORY');
export const EVENT_RSVP_REPOSITORY = Symbol('EVENT_RSVP_REPOSITORY');
export const ANNOUNCEMENT_REPOSITORY = Symbol('ANNOUNCEMENT_REPOSITORY');
export const ADVISORY_REPOSITORY = Symbol('ADVISORY_REPOSITORY');
export const LISTING_REPOSITORY = Symbol('LISTING_REPOSITORY');
export const ORDER_REPOSITORY = Symbol('ORDER_REPOSITORY');
export const REVIEW_REPOSITORY = Symbol('REVIEW_REPOSITORY');
export const CREDIT_PROFILE_REPOSITORY = Symbol('CREDIT_PROFILE_REPOSITORY');
export const DOCUMENT_REPOSITORY = Symbol('DOCUMENT_REPOSITORY');
export const NOTIFICATION_REPOSITORY = Symbol('NOTIFICATION_REPOSITORY');
export const NOTIFICATION_PREFERENCE_REPOSITORY = Symbol('NOTIFICATION_PREFERENCE_REPOSITORY');
export const DELIVERY_LOG_REPOSITORY = Symbol('DELIVERY_LOG_REPOSITORY');
export const AUDIT_REPOSITORY = Symbol('AUDIT_REPOSITORY');
export const OUTBOX_REPOSITORY = Symbol('OUTBOX_REPOSITORY');
export const COMMODITY_PRICE_REPOSITORY = Symbol('COMMODITY_PRICE_REPOSITORY');

// Engagement wave (P2b): services marketplace, programmes, pathways, knowledge, search depth.
export const SUPPLIER_REPOSITORY = Symbol('SUPPLIER_REPOSITORY');
export const SERVICE_OFFERING_REPOSITORY = Symbol('SERVICE_OFFERING_REPOSITORY');
export const SERVICE_BOOKING_REPOSITORY = Symbol('SERVICE_BOOKING_REPOSITORY');
export const SERVICE_REVIEW_REPOSITORY = Symbol('SERVICE_REVIEW_REPOSITORY');
export const PROGRAMME_COHORT_REPOSITORY = Symbol('PROGRAMME_COHORT_REPOSITORY');
export const PROGRAMME_ENROLMENT_REPOSITORY = Symbol('PROGRAMME_ENROLMENT_REPOSITORY');
export const PROGRAMME_MILESTONE_REPOSITORY = Symbol('PROGRAMME_MILESTONE_REPOSITORY');
export const MILESTONE_PROGRESS_REPOSITORY = Symbol('MILESTONE_PROGRESS_REPOSITORY');
export const RUBRIC_CRITERION_REPOSITORY = Symbol('RUBRIC_CRITERION_REPOSITORY');
export const JUDGE_ASSIGNMENT_REPOSITORY = Symbol('JUDGE_ASSIGNMENT_REPOSITORY');
export const JUDGE_SCORE_REPOSITORY = Symbol('JUDGE_SCORE_REPOSITORY');
export const COHORT_THREAD_REPOSITORY = Symbol('COHORT_THREAD_REPOSITORY');
export const COHORT_THREAD_POST_REPOSITORY = Symbol('COHORT_THREAD_POST_REPOSITORY');
export const PATHWAY_TEMPLATE_REPOSITORY = Symbol('PATHWAY_TEMPLATE_REPOSITORY');
export const PATHWAY_STAGE_REPOSITORY = Symbol('PATHWAY_STAGE_REPOSITORY');
export const PATHWAY_ENROLMENT_REPOSITORY = Symbol('PATHWAY_ENROLMENT_REPOSITORY');
export const STAGE_PROGRESS_REPOSITORY = Symbol('STAGE_PROGRESS_REPOSITORY');
export const CAMPUS_CLUB_REPOSITORY = Symbol('CAMPUS_CLUB_REPOSITORY');
export const CAMPUS_CLUB_MEMBERSHIP_REPOSITORY = Symbol('CAMPUS_CLUB_MEMBERSHIP_REPOSITORY');
export const KNOWLEDGE_RESOURCE_REPOSITORY = Symbol('KNOWLEDGE_RESOURCE_REPOSITORY');
export const PODCAST_EPISODE_REPOSITORY = Symbol('PODCAST_EPISODE_REPOSITORY');
export const WEBINAR_REPOSITORY = Symbol('WEBINAR_REPOSITORY');
export const WEBINAR_REGISTRATION_REPOSITORY = Symbol('WEBINAR_REGISTRATION_REPOSITORY');
export const SEARCH_QUERY_REPOSITORY = Symbol('SEARCH_QUERY_REPOSITORY');
// Wave P5c: recommendation feedback + analytics data marts.
export const RECOMMENDATION_FEEDBACK_REPOSITORY = Symbol('RECOMMENDATION_FEEDBACK_REPOSITORY');
export const ANALYTICS_MART_REPOSITORY = Symbol('ANALYTICS_MART_REPOSITORY');

// Wave P2a: marketplace depth (escrow/invoicing/logistics) + finance/credit.
export const ESCROW_REPOSITORY = Symbol('ESCROW_REPOSITORY');
// Stage 23: recorded escrow payout attempts (release/refund rail).
export const ESCROW_PAYOUT_REPOSITORY = Symbol('ESCROW_PAYOUT_REPOSITORY');
export const INVOICE_REPOSITORY = Symbol('INVOICE_REPOSITORY');
export const SHIPMENT_REPOSITORY = Symbol('SHIPMENT_REPOSITORY');
export const LEDGER_ACCOUNT_REPOSITORY = Symbol('LEDGER_ACCOUNT_REPOSITORY');
export const LEDGER_ENTRY_REPOSITORY = Symbol('LEDGER_ENTRY_REPOSITORY');
export const CREDIT_SCORE_REPOSITORY = Symbol('CREDIT_SCORE_REPOSITORY');
export const LENDER_REPOSITORY = Symbol('LENDER_REPOSITORY');
export const LOAN_APPLICATION_REPOSITORY = Symbol('LOAN_APPLICATION_REPOSITORY');
export const REPAYMENT_SCHEDULE_REPOSITORY = Symbol('REPAYMENT_SCHEDULE_REPOSITORY');